# 服务器配置
server:
  port: 8080

# Spring配置
spring:
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mind_capture?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  
  # Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      password: 
      database: 0
      timeout: 10s

# MyBatis Plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath*:/mapper/**/*.xml

# JWT配置
jwt:
  # JWT加解密使用的密钥
  secret: mindcapture-jwt-secret-key-2024
  # JWT的有效期（单位：秒）
  expiration: 86400
  # JWT的签发者
  issuer: mindcapture

# 验证码配置
kaptcha:
  border: "yes"
  border.color: 105,179,90
  textproducer.font.color: blue
  textproducer.font.size: 30
  textproducer.font.names: 宋体,楷体,微软雅黑
  textproducer.char.length: 4
  image.width: 120
  image.height: 40
  session.key: kaptcha_code
  # 验证码有效期：120秒
  expiration: 120